# Copyright 2013-2024 Lawrence Livermore National Security, LLC and other
# Spack Project Developers. See the top-level COPYRIGHT file for details.
#
# SPDX-License-Identifier: (Apache-2.0 OR MIT)

from spack.package import *


class PerlPerlCritic(PerlPackage):
    """Critique Perl source code for best-practices."""

    homepage = "https://metacpan.org/pod/Perl::Critic"
    url = "https://cpan.metacpan.org/authors/id/P/PE/PETDANCE/Perl-Critic-1.152.tar.gz"

    maintainers("greenc-FNAL", "EbiArnie", "gartung", "marcmengel", "vito")

    license("Artistic-1.0-Perl OR GPL-1.0-or-later")

    version("1.152", sha256="e5bfaf67f61a2a6a0ed343f0403b19f515b4890eed6272abaab707749c5e5e1e")
    version("1.140", sha256="bfeef0aa36f0941682a607212593db530b2c8a5499f6dc7d41f7e61a8ebdfddb")
    version("1.139_01", sha256="6fcbf8ab7e9579e3985fc87c92e3ec57eafdc7c609d3e39ed7331675335b1703")

    provides("perl-perl-critic-annotation")
    provides("perl-perl-critic-command")
    provides("perl-perl-critic-config")
    provides("perl-perl-critic-document")
    provides("perl-perl-critic-exception")
    provides("perl-perl-critic-exception-aggregateconfiguration")
    provides("perl-perl-critic-exception-configuration")
    provides("perl-perl-critic-exception-configuration-generic")
    provides("perl-perl-critic-exception-configuration-nonexistentpolicy")
    provides("perl-perl-critic-exception-configuration-option")
    provides("perl-perl-critic-exception-configuration-option-global")
    provides("perl-perl-critic-exception-configuration-option-global-extraparameter")
    provides("perl-perl-critic-exception-configuration-option-global-parametervalue")
    provides("perl-perl-critic-exception-configuration-option-policy")
    provides("perl-perl-critic-exception-configuration-option-policy-extraparameter")
    provides("perl-perl-critic-exception-configuration-option-policy-parametervalue")
    provides("perl-perl-critic-exception-fatal")
    provides("perl-perl-critic-exception-fatal-generic")
    provides("perl-perl-critic-exception-fatal-internal")
    provides("perl-perl-critic-exception-fatal-policydefinition")
    provides("perl-perl-critic-exception-io")
    provides("perl-perl-critic-exception-parse")
    provides("perl-perl-critic-optionsprocessor")
    provides("perl-perl-critic-policy")
    provides("perl-perl-critic-policy-builtinfunctions-prohibitbooleangrep")
    provides("perl-perl-critic-policy-builtinfunctions-prohibitcomplexmappings")
    provides("perl-perl-critic-policy-builtinfunctions-prohibitlvaluesubstr")
    provides("perl-perl-critic-policy-builtinfunctions-prohibitreversesortblock")
    provides("perl-perl-critic-policy-builtinfunctions-prohibitshiftref")
    provides("perl-perl-critic-policy-builtinfunctions-prohibitsleepviaselect")
    provides("perl-perl-critic-policy-builtinfunctions-prohibitstringyeval")
    provides("perl-perl-critic-policy-builtinfunctions-prohibitstringysplit")
    provides("perl-perl-critic-policy-builtinfunctions-prohibituniversalcan")
    provides("perl-perl-critic-policy-builtinfunctions-prohibituniversalisa")
    provides("perl-perl-critic-policy-builtinfunctions-prohibituselesstopic")
    provides("perl-perl-critic-policy-builtinfunctions-prohibitvoidgrep")
    provides("perl-perl-critic-policy-builtinfunctions-prohibitvoidmap")
    provides("perl-perl-critic-policy-builtinfunctions-requireblockgrep")
    provides("perl-perl-critic-policy-builtinfunctions-requireblockmap")
    provides("perl-perl-critic-policy-builtinfunctions-requireglobfunction")
    provides("perl-perl-critic-policy-builtinfunctions-requiresimplesortblock")
    provides("perl-perl-critic-policy-classhierarchies-prohibitautoloading")
    provides("perl-perl-critic-policy-classhierarchies-prohibitexplicitisa")
    provides("perl-perl-critic-policy-classhierarchies-prohibitoneargbless")
    provides("perl-perl-critic-policy-codelayout-prohibithardtabs")
    provides("perl-perl-critic-policy-codelayout-prohibitparenswithbuiltins")
    provides("perl-perl-critic-policy-codelayout-prohibitquotedwordlists")
    provides("perl-perl-critic-policy-codelayout-prohibittrailingwhitespace")
    provides("perl-perl-critic-policy-codelayout-requireconsistentnewlines")
    provides("perl-perl-critic-policy-codelayout-requiretidycode")
    provides("perl-perl-critic-policy-codelayout-requiretrailingcommas")
    provides("perl-perl-critic-policy-controlstructures-prohibitcstyleforloops")
    provides("perl-perl-critic-policy-controlstructures-prohibitcascadingifelse")
    provides("perl-perl-critic-policy-controlstructures-prohibitdeepnests")
    provides("perl-perl-critic-policy-controlstructures-prohibitlabelswithspecialblocknames")
    provides("perl-perl-critic-policy-controlstructures-prohibitmutatinglistfunctions")
    provides(
        "perl-perl-critic-policy-controlstructures-"
        "prohibitnegativeexpressionsinunlessanduntilconditions"
    )
    provides("perl-perl-critic-policy-controlstructures-prohibitpostfixcontrols")
    provides("perl-perl-critic-policy-controlstructures-prohibitunlessblocks")
    provides("perl-perl-critic-policy-controlstructures-prohibitunreachablecode")
    provides("perl-perl-critic-policy-controlstructures-prohibituntilblocks")
    provides("perl-perl-critic-policy-controlstructures-prohibityadaoperator")
    provides("perl-perl-critic-policy-documentation-podspelling")
    provides("perl-perl-critic-policy-documentation-requirepackagematchespodname")
    provides("perl-perl-critic-policy-documentation-requirepodatend")
    provides("perl-perl-critic-policy-documentation-requirepodsections")
    provides("perl-perl-critic-policy-errorhandling-requirecarping")
    provides("perl-perl-critic-policy-errorhandling-requirecheckingreturnvalueofeval")
    provides("perl-perl-critic-policy-inputoutput-prohibitbacktickoperators")
    provides("perl-perl-critic-policy-inputoutput-prohibitbarewordfilehandles")
    provides("perl-perl-critic-policy-inputoutput-prohibitexplicitstdin")
    provides("perl-perl-critic-policy-inputoutput-prohibitinteractivetest")
    provides("perl-perl-critic-policy-inputoutput-prohibitjoinedreadline")
    provides("perl-perl-critic-policy-inputoutput-prohibitoneargselect")
    provides("perl-perl-critic-policy-inputoutput-prohibitreadlineinforloop")
    provides("perl-perl-critic-policy-inputoutput-prohibittwoargopen")
    provides("perl-perl-critic-policy-inputoutput-requirebracedfilehandlewithprint")
    provides("perl-perl-critic-policy-inputoutput-requirebriefopen")
    provides("perl-perl-critic-policy-inputoutput-requirecheckedclose")
    provides("perl-perl-critic-policy-inputoutput-requirecheckedopen")
    provides("perl-perl-critic-policy-inputoutput-requirecheckedsyscalls")
    provides("perl-perl-critic-policy-inputoutput-requireencodingwithutf8layer")
    provides("perl-perl-critic-policy-miscellanea-prohibitformats")
    provides("perl-perl-critic-policy-miscellanea-prohibitties")
    provides("perl-perl-critic-policy-miscellanea-prohibitunrestrictednocritic")
    provides("perl-perl-critic-policy-miscellanea-prohibituselessnocritic")
    provides("perl-perl-critic-policy-modules-prohibitautomaticexportation")
    provides("perl-perl-critic-policy-modules-prohibitconditionalusestatements")
    provides("perl-perl-critic-policy-modules-prohibitevilmodules")
    provides("perl-perl-critic-policy-modules-prohibitexcessmaincomplexity")
    provides("perl-perl-critic-policy-modules-prohibitmultiplepackages")
    provides("perl-perl-critic-policy-modules-requirebarewordincludes")
    provides("perl-perl-critic-policy-modules-requireendwithone")
    provides("perl-perl-critic-policy-modules-requireexplicitpackage")
    provides("perl-perl-critic-policy-modules-requirefilenamematchespackage")
    provides("perl-perl-critic-policy-modules-requirenomatchvarswithuseenglish")
    provides("perl-perl-critic-policy-modules-requireversionvar")
    provides("perl-perl-critic-policy-namingconventions-capitalization")
    provides("perl-perl-critic-policy-namingconventions-prohibitambiguousnames")
    provides("perl-perl-critic-policy-objects-prohibitindirectsyntax")
    provides("perl-perl-critic-policy-references-prohibitdoublesigils")
    provides("perl-perl-critic-policy-regularexpressions-prohibitcapturewithouttest")
    provides("perl-perl-critic-policy-regularexpressions-prohibitcomplexregexes")
    provides("perl-perl-critic-policy-regularexpressions-prohibitenumeratedclasses")
    provides("perl-perl-critic-policy-regularexpressions-prohibitescapedmetacharacters")
    provides("perl-perl-critic-policy-regularexpressions-prohibitfixedstringmatches")
    provides("perl-perl-critic-policy-regularexpressions-prohibitsinglecharalternation")
    provides("perl-perl-critic-policy-regularexpressions-prohibitunusedcapture")
    provides("perl-perl-critic-policy-regularexpressions-prohibitunusualdelimiters")
    provides("perl-perl-critic-policy-regularexpressions-prohibituselesstopic")
    provides("perl-perl-critic-policy-regularexpressions-requirebracesformultiline")
    provides("perl-perl-critic-policy-regularexpressions-requiredotmatchanything")
    provides("perl-perl-critic-policy-regularexpressions-requireextendedformatting")
    provides("perl-perl-critic-policy-regularexpressions-requirelineboundarymatching")
    provides("perl-perl-critic-policy-subroutines-prohibitampersandsigils")
    provides("perl-perl-critic-policy-subroutines-prohibitbuiltinhomonyms")
    provides("perl-perl-critic-policy-subroutines-prohibitexcesscomplexity")
    provides("perl-perl-critic-policy-subroutines-prohibitexplicitreturnundef")
    provides("perl-perl-critic-policy-subroutines-prohibitmanyargs")
    provides("perl-perl-critic-policy-subroutines-prohibitnestedsubs")
    provides("perl-perl-critic-policy-subroutines-prohibitreturnsort")
    provides("perl-perl-critic-policy-subroutines-prohibitsubroutineprototypes")
    provides("perl-perl-critic-policy-subroutines-prohibitunusedprivatesubroutines")
    provides("perl-perl-critic-policy-subroutines-protectprivatesubs")
    provides("perl-perl-critic-policy-subroutines-requireargunpacking")
    provides("perl-perl-critic-policy-subroutines-requirefinalreturn")
    provides("perl-perl-critic-policy-testinganddebugging-prohibitnostrict")
    provides("perl-perl-critic-policy-testinganddebugging-prohibitnowarnings")
    provides("perl-perl-critic-policy-testinganddebugging-prohibitprolongedstrictureoverride")
    provides("perl-perl-critic-policy-testinganddebugging-requiretestlabels")
    provides("perl-perl-critic-policy-testinganddebugging-requireusestrict")
    provides("perl-perl-critic-policy-testinganddebugging-requireusewarnings")
    provides("perl-perl-critic-policy-valuesandexpressions-prohibitcommaseparatedstatements")
    provides("perl-perl-critic-policy-valuesandexpressions-prohibitcomplexversion")
    provides("perl-perl-critic-policy-valuesandexpressions-prohibitconstantpragma")
    provides("perl-perl-critic-policy-valuesandexpressions-prohibitemptyquotes")
    provides("perl-perl-critic-policy-valuesandexpressions-prohibitescapedcharacters")
    provides("perl-perl-critic-policy-valuesandexpressions-prohibitimplicitnewlines")
    provides("perl-perl-critic-policy-valuesandexpressions-prohibitinterpolationofliterals")
    provides("perl-perl-critic-policy-valuesandexpressions-prohibitleadingzeros")
    provides("perl-perl-critic-policy-valuesandexpressions-prohibitlongchainsofmethodcalls")
    provides("perl-perl-critic-policy-valuesandexpressions-prohibitmagicnumbers")
    provides("perl-perl-critic-policy-valuesandexpressions-prohibitmismatchedoperators")
    provides("perl-perl-critic-policy-valuesandexpressions-prohibitmixedbooleanoperators")
    provides("perl-perl-critic-policy-valuesandexpressions-prohibitnoisyquotes")
    provides(
        "perl-perl-critic-policy-valuesandexpressions-prohibitquotesasquotelikeoperatordelimiters"
    )
    provides(
        "perl-perl-critic-policy-valuesandexpressions-prohibitspecialliteralheredocterminator"
    )
    provides("perl-perl-critic-policy-valuesandexpressions-prohibitversionstrings")
    provides("perl-perl-critic-policy-valuesandexpressions-requireconstantversion")
    provides("perl-perl-critic-policy-valuesandexpressions-requireinterpolationofmetachars")
    provides("perl-perl-critic-policy-valuesandexpressions-requirenumberseparators")
    provides("perl-perl-critic-policy-valuesandexpressions-requirequotedheredocterminator")
    provides("perl-perl-critic-policy-valuesandexpressions-requireuppercaseheredocterminator")
    provides("perl-perl-critic-policy-variables-prohibitaugmentedassignmentindeclaration")
    provides("perl-perl-critic-policy-variables-prohibitconditionaldeclarations")
    provides("perl-perl-critic-policy-variables-prohibitevilvariables")
    provides("perl-perl-critic-policy-variables-prohibitlocalvars")
    provides("perl-perl-critic-policy-variables-prohibitmatchvars")
    provides("perl-perl-critic-policy-variables-prohibitpackagevars")
    provides("perl-perl-critic-policy-variables-prohibitperl4packagenames")
    provides("perl-perl-critic-policy-variables-prohibitpunctuationvars")
    provides("perl-perl-critic-policy-variables-prohibitreusednames")
    provides("perl-perl-critic-policy-variables-prohibitunusedvariables")
    provides("perl-perl-critic-policy-variables-protectprivatevars")
    provides("perl-perl-critic-policy-variables-requireinitializationforlocalvars")
    provides("perl-perl-critic-policy-variables-requirelexicalloopiterators")
    provides("perl-perl-critic-policy-variables-requirelocalizedpunctuationvars")
    provides("perl-perl-critic-policy-variables-requirenegativeindices")
    provides("perl-perl-critic-policyconfig")
    provides("perl-perl-critic-policyfactory")
    provides("perl-perl-critic-policylisting")
    provides("perl-perl-critic-policyparameter")
    provides("perl-perl-critic-policyparameter-behavior")
    provides("perl-perl-critic-policyparameter-behavior-boolean")
    provides("perl-perl-critic-policyparameter-behavior-enumeration")
    provides("perl-perl-critic-policyparameter-behavior-integer")
    provides("perl-perl-critic-policyparameter-behavior-string")
    provides("perl-perl-critic-policyparameter-behavior-stringlist")
    provides("perl-perl-critic-profileprototype")
    provides("perl-perl-critic-statistics")
    provides("perl-perl-critic-testutils")
    provides("perl-perl-critic-theme")
    provides("perl-perl-critic-themelisting")
    provides("perl-perl-critic-userprofile")
    provides("perl-perl-critic-utils")
    provides("perl-perl-critic-utils-constants")
    provides("perl-perl-critic-utils-dataconversion")
    provides("perl-perl-critic-utils-mccabe")
    provides("perl-perl-critic-utils-pod")
    provides("perl-perl-critic-utils-pod-parseinteriorsequence")
    provides("perl-perl-critic-utils-ppi")
    provides("perl-perl-critic-utils-perl")
    provides("perl-perl-critic-violation")
    provides("perl-test-perl-critic-policy")

    depends_on("perl-readonly@2:", type=("build", "run", "test"))
    depends_on("perl-file-which", type=("build", "run", "test"))
    depends_on("perl-io-string", type=("build", "run", "test"))
    depends_on("perl-task-weaken", type=("build", "run", "test"))
    depends_on("perl-ppi-node@1.265:", type=("build", "run", "test"))
    depends_on("perl-module-pluggable@3.1:", type=("build", "run", "test"))
    depends_on("perl-test-deep", type=("build", "test"))
    depends_on("perl-config-tiny@2:", type=("build", "run", "test"))
    depends_on("perl-ppix-utilities-statement@1.1:", type=("build", "run", "test"))
    depends_on("perl-ppi-document-file@1.265:", type=("build", "run", "test"))
    depends_on("perl-scalar-util", type=("build", "run", "test"))
    depends_on("perl-list-moreutils@0.19:", type=("build", "run", "test"))
    depends_on("perl-pod-parser", type=("build", "run", "test"))
    depends_on("perl-pod-spell@1:", type=("build", "run", "test"))
    depends_on("perl-list-util", type=("build", "run", "test"))
    depends_on("perl-ppix-utilities-node@1.1:", type=("build", "run", "test"))
    depends_on("perl-ppi-token-quote-single@1.265:", type=("build", "run", "test"))
    depends_on("perl-string-format@1.18:", type=("build", "run", "test"))
    depends_on("perl-ppix-quotelike", type=("build", "run", "test"))
    depends_on("perl-ppix-regexp@0.27:", type=("build", "run", "test"))
    depends_on("perl-ppi@1.265:", type=("build", "run", "test"))
    depends_on("perl-pod-plaintext", type=("build", "run", "test"))
    depends_on("perl-exception-class@1.23:", type=("build", "run", "test"))
    depends_on("perl@5.10.1:", type=("build", "run", "test"))
    depends_on("perl-pod-select", type=("build", "run", "test"))
    depends_on("perl-b-keywords@1.5:", type=("build", "run", "test"))
    depends_on("perl-module-build@0.42.4:", type=("build", "run"))
    depends_on("perl-ppi-token-whitespace@1.265:", type=("build", "run", "test"))
    depends_on("perl-ppi-document@1.265:", type=("build", "run", "test"))
    depends_on("perl-ppix-regexp-util@0.68:", type=("build", "run", "test"))
    depends_on("perl-perl-tidy", type=("build", "run", "test"))
