# Copyright 2013-2024 Lawrence Livermore National Security, LLC and other
# Spack Project Developers. See the top-level COPYRIGHT file for details.
#
# SPDX-License-Identifier: (Apache-2.0 OR MIT)

from spack.package import *


class PerlPpi(PerlPackage):
    """Parse, Analyze and Manipulate Perl (without perl)"""

    homepage = "https://metacpan.org/pod/PPI"
    url = "https://cpan.metacpan.org/authors/id/M/MI/MITHALDU/PPI-1.277.tar.gz"

    maintainers("greenc-FNAL", "EbiArnie", "gartung", "marcmengel", "vito")

    license("Artistic-1.0-Perl OR GPL-1.0-or-later")

    version("1.277", sha256="87c79f83b6876e206051965d5019d2507c551f819a86750080ec7ec43b2e0af8")
    version("1.276", sha256="657655470e78b7c5b7660f7dec82893489c2e2d880e449135613da3b37500f01")
    version("1.275", sha256="71ef406ce6d0c8ff9545fe308740c958d7892851677ff9c61bb967cd466130d9")

    provides("perl-ppi-cache")
    provides("perl-ppi-document")
    provides("perl-ppi-document-file")
    provides("perl-ppi-document-fragment")
    provides("perl-ppi-document-normalized")
    provides("perl-ppi-dumper")
    provides("perl-ppi-element")
    provides("perl-ppi-exception")
    provides("perl-ppi-exception-parserrejection")
    provides("perl-ppi-find")
    provides("perl-ppi-lexer")
    provides("perl-ppi-node")
    provides("perl-ppi-normal")
    provides("perl-ppi-normal-standard")
    provides("perl-ppi-singletons")
    provides("perl-ppi-statement")
    provides("perl-ppi-statement-break")
    provides("perl-ppi-statement-compound")
    provides("perl-ppi-statement-data")
    provides("perl-ppi-statement-end")
    provides("perl-ppi-statement-expression")
    provides("perl-ppi-statement-given")
    provides("perl-ppi-statement-include")
    provides("perl-ppi-statement-include-perl6")
    provides("perl-ppi-statement-null")
    provides("perl-ppi-statement-package")
    provides("perl-ppi-statement-scheduled")
    provides("perl-ppi-statement-sub")
    provides("perl-ppi-statement-unknown")
    provides("perl-ppi-statement-unmatchedbrace")
    provides("perl-ppi-statement-variable")
    provides("perl-ppi-statement-when")
    provides("perl-ppi-structure")
    provides("perl-ppi-structure-block")
    provides("perl-ppi-structure-condition")
    provides("perl-ppi-structure-constructor")
    provides("perl-ppi-structure-for")
    provides("perl-ppi-structure-given")
    provides("perl-ppi-structure-list")
    provides("perl-ppi-structure-subscript")
    provides("perl-ppi-structure-unknown")
    provides("perl-ppi-structure-when")
    provides("perl-ppi-token")
    provides("perl-ppi-token-arrayindex")
    provides("perl-ppi-token-attribute")
    provides("perl-ppi-token-bom")
    provides("perl-ppi-token-cast")
    provides("perl-ppi-token-comment")
    provides("perl-ppi-token-dashedword")
    provides("perl-ppi-token-data")
    provides("perl-ppi-token-end")
    provides("perl-ppi-token-heredoc")
    provides("perl-ppi-token-label")
    provides("perl-ppi-token-magic")
    provides("perl-ppi-token-number")
    provides("perl-ppi-token-number-binary")
    provides("perl-ppi-token-number-exp")
    provides("perl-ppi-token-number-float")
    provides("perl-ppi-token-number-hex")
    provides("perl-ppi-token-number-octal")
    provides("perl-ppi-token-number-version")
    provides("perl-ppi-token-operator")
    provides("perl-ppi-token-pod")
    provides("perl-ppi-token-prototype")
    provides("perl-ppi-token-quote")
    provides("perl-ppi-token-quote-double")
    provides("perl-ppi-token-quote-interpolate")
    provides("perl-ppi-token-quote-literal")
    provides("perl-ppi-token-quote-single")
    provides("perl-ppi-token-quotelike")
    provides("perl-ppi-token-quotelike-backtick")
    provides("perl-ppi-token-quotelike-command")
    provides("perl-ppi-token-quotelike-readline")
    provides("perl-ppi-token-quotelike-regexp")
    provides("perl-ppi-token-quotelike-words")
    provides("perl-ppi-token-regexp")
    provides("perl-ppi-token-regexp-match")
    provides("perl-ppi-token-regexp-substitute")
    provides("perl-ppi-token-regexp-transliterate")
    provides("perl-ppi-token-separator")
    provides("perl-ppi-token-structure")
    provides("perl-ppi-token-symbol")
    provides("perl-ppi-token-unknown")
    provides("perl-ppi-token-whitespace")
    provides("perl-ppi-token-word")
    provides("perl-ppi-tokenizer")
    provides("perl-ppi-transform")
    provides("perl-ppi-transform-updatecopyright")
    provides("perl-ppi-util")
    provides("perl-ppi-xsaccessor")

    depends_on("perl@5.6:", type="run")

    depends_on("perl-extutils-makemaker", type=("build", "test"))

    depends_on("perl-test-object@0.7:", type=("build", "test"))
    depends_on("perl-params-util@1.0:", type=("build", "run", "test"))
    depends_on("perl-class-inspector@1.22:", type=("build", "test"))
    depends_on("perl-clone@0.30:", type=("build", "run", "test"))
    depends_on("perl-task-weaken", type=("build", "run", "test"))
    depends_on("perl-test-subcalls@1.7:", type=("build", "test"))
    depends_on("perl-test-nowarnings", type=("build", "test"))
    depends_on("perl-digest-md5@2.35:", type=("build", "run", "test"))
    depends_on("perl-scalar-util", type=("build", "run", "test"))
    depends_on("perl-list-util@1.33:", type=("build", "run", "test"))
